version: "3"
services:
  tray_api:
    build: ./api
    container_name: tray_api
    volumes:
      - ./api:/var/www
    networks:
      - network_tray

  tray_server:
    build: ./api/.docker/nginx
    container_name: tray_server
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www
    depends_on:
      - tray_api
    networks:
      - network_tray

  tray_db:
    image: mysql:5.7.22
    container_name: tray_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "tray_db"
      MYSQL_ROOT_PASSWORD: "tray_pass"
      MYSQL_PASSWORD: "tray_pass"
      MYSQL_USER: "tray_user"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - nova_base_tray:/var/lib/mysql/
    networks:
      - network_tray

  tray_front:
    container_name: tray_front
    build: ./front
#    entrypoint: docker/entrypoint.sh
    restart: always
    ports:
      - "3001:5000"
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/home/node/app
      - '/home/node/app/node_modules'
    depends_on:
      - tray_api
    networks:
      - network_tray

networks:
  network_tray:
    driver: bridge

volumes:
  nova_base_tray:
    driver: local
